version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.0

    steps:
      - checkout

      - ruby/install-deps

      - run:
          name: Run bacon tests
          command: bundle exec rake test

      - ruby/rspec-test
